### PR TITLE
Implement DryWetDualMixer

### PR DESCRIPTION
**Pull request by jcavar**
This allows for independent control of dry and wet.
The existing DryWetMixer API is unchanged.

### CODE REVIEW

**Comment by aure** [comment]
Could you add tests for this feature?

**Comment by jcavar** [comment]
Hey @aure. This is implicitly tested through `DryWetMixer` already, but I am happy to add separate tests if you think it is valuable. E.g.:

- testBothInputs1
- testBothInputs0

Let me know.

**Comment by aure** [comment]
Hi, it turns out this breaks DryWetMixer in a very odd way. The tests all pass, but if you try the Cookbook, you'll notice that the mix slider does nothing. The dry and wet ramps never get updated from their default of 0.5. It's been driving me crazy.

**Comment by aure** [comment]
Your way passed the tests! I can't blame you for thinking it should have worked. And I couldn't figure out why after much hair pulling, which is why I went with two separate DSP implmementations.

**Pull request closed without merging**
